model_list:
  - model_name: gpt-3.5-turbo-1106
    litellm_params:
      model: gpt-3.5-turbo-1106

litellm_settings:
  callbacks: scrapi_validated_tool_use.LiteLLMSCRAPIValidatedToolUse
  callback_params_cls: scrapi_validated_tool_use.LiteLLMSCRAPIValidatedToolUseParams
  callback_params:
    # For Phase 0 the relying party is routes added to SCRAPI
    tool_use_relying_party:
      url: 'http://localhost:8000'
    scrapi_instances:
    # - url: 'https://scitt.unstable.chadig.com'
    - url: 'http://localhost:8000'
      # TODO urn of transparent statement for validation policy
      validation_subject: 'validation.tool.proxy.llm'
      # TODO urn of transparent statement for index policy
      tool_index_subject: 'tool.proxy.llm'
