model_list:
  - model_name: gpt-3.5-turbo-1106
    litellm_params:
      model: gpt-3.5-turbo-1106

litellm_settings:
  callbacks:
    - - scrapi_validated_tool_use.LiteLLMSCRAPIValidatedToolUse
      - scrapi_validated_tool_use.LiteLLMSCRAPIValidatedToolUseParams
      - scrapi_instances:
        # - url: 'https://scrapi.unstable.chadig.com'
        - url: 'http://localhost:8000'
    - - scrapi_tool_index.LiteLLMSCRAPIToolIndex
      - scrapi_tool_index.LiteLLMSCRAPIToolIndexParams
      - scrapi_instances:
        # - url: 'https://scrapi.unstable.chadig.com'
        - url: 'http://localhost:8000'
